server:
  port: 8080
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_label?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
    schema: classpath:sql/table.sql
    data: classpath:sql/data.sql
    initialization-mode: ALWAYS
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.stp.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
